TRAINING:
  image_lr: 0.0001
  gene_lr: 0.001
  batch_size: 32
  epochs: 100

  loss: "rankInfoNCETS"
  alpha: 5
  beta: 1
  ema_momentum: 0.96
  gene_image_flag: True

MODEL:
  pretrained_model: "UNI"
  pretrained_model_path: "./model_checkpoint/UNI"
  gene_input_dim: 447

DATASET:
  train_dataset: "breast"
  train_dataset_path: "./data/HEST/Breast"
  gene_path: "./data/HEST/Breast/ST-expression-survival/8n"
  task: "survival"
  smoothing: "8n"
  num_workers: 4


ACCELERATOR: "gpu"
DEVICE: [0]

EXPERIMENT_DIR: "./experiment_breast"